// Auto-generated by pyxel-wrapper-ts-bindgen
import { instancePromise } from './instance.js';

let instance;
const ready = instancePromise.then((inst) => {
  instance = inst.exports;
});


export function init(width: number, height: number): void {
  return (instance as any).init(width, height);
}

export function cls(color: number): void {
  return (instance as any).cls(color);
}

export { ready };