[workspace]
members =  ["pyxel-platform", "pyxel-engine", "pyxel-wrapper-ts", "pyxel-wrapper-ts-bindgen", "pyxel-wrapper-ts-types", "pyxel-wrapper-ts-pack"]
resolver = "2"

[workspace.dependencies]
getrandom = { version = "0.3.2", default-features = false, features = ["wasm_js"] }
